
FROM node:22.2.0-alpine AS build



WORKDIR /app

COPY package.json package-lock.json ./




RUN npm install

COPY . .

RUN npm run build


FROM node:22.2.0-alpine

WORKDIR /app


RUN npm install -g serve


COPY --from=build /app/dist ./dist

EXPOSE 8000

CMD ["serve", "-s", "dist", "-l", "8000"]
